### ISSUE TITLE
Unclear request method for `/securesession/refresh`

### ISSUE THREAD

**Issue by hagould** [WICG/dbsc#78] opened 2024-10-01 17:33 UTC
The basic DBSC spec describes both `GET` and `POST` requests to `/securesession/refresh`, the [high level overview](https://github.com/WICG/dbsc?tab=readme-ov-file#high-level-overview) only uses `GET` with headers, but the [refresh procedure](https://github.com/WICG/dbsc?tab=readme-ov-file#refresh-procedure) is showing `POST` for the scenario where the server chooses to end the session. Is one of these outdated, or otherwise, how would an RP hint to the client which type of request to make?

**Comment by chen-chao** [comment] 2024-10-21 06:30
It seems the chart in [high level overview](https://github.com/WICG/dbsc?tab=readme-ov-file#high-level-overview) is outdated. By design the registration and refresh procedure are very similar, so they should both use `POST`.

**Comment by kmonsen** [comment] 2024-10-21 23:40
Thank you both, I have updated both the text and diagram. Please let me know if I missed a place, or close this issue if it looks OK now.

**Closed** 2024-12-12 17:44 UTC
